# jekyll settings
permalink: pretty
exclude: [Gemfile, Gemfile.lock, Guardfile, Readme.md, CNAME, '*.scss']
excerpt_separator: "\n\n"
kramdown:
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

title: Chen Yangjian
description: Everything about Chen Yangjian.
url: https://cyj.me
baseurl: ""
repository: cyjake/cyjake.github.io
author:
  name: Chen Yangjian
  uri: https://cyj.me
feed:
  path: feed/atom.xml
